feat(nav): 添加导航栏切换字体功能
project-trans/vitepress-theme-project-trans pull request #9
Opened 2024-10-23 13:00 UTC by Leetfs

2024-10-23 17:10 UTC, saeziae commented on src/style.css
> +@import 'https://fonts-av1.pages.dev/fonts.css';
pages dev 在老中被屏蔽了，還不如 google fonts 了

2024-10-23 17:10 UTC, saeziae commented on src/plugins/fontSwitcher.js
> +  // 字体映射表
開頭加個 黑體，宋體 對應 font-family sans 和 serif，這倆不需要從網上獲取。

2024-10-23 17:39 UTC, saeziae requested changes

2024-10-23 17:39 UTC, saeziae commented on src/plugins/fontSwitcher.js
> +  '黑体': 'font-family sans',
```suggestion
  '黑体': 'sans',
```

2024-10-23 17:39 UTC, saeziae commented on src/plugins/fontSwitcher.js
> +  '黑体': 'font-family sans',
6

2024-10-23 17:41 UTC, Leetfs commented on src/plugins/fontSwitcher.js
> +  '黑体': 'font-family sans',
草（）

2024-10-23 17:42 UTC, saeziae approved these changes

2024-10-24 05:12 UTC, Cryolitia approved these changes

2024-10-24 05:12 UTC, merged